export enum RouteName {
  DEMO_HOME = 'CoolWallet Demo App',
  BLUETOOTH_SCAN = 'BluetoothScan',
  REFRESH_APP_KEY_PAIR = 'Refresh App Key Pair',
  RESET_CARD = 'Reset Card',
  REGISTER_CARD = 'Register Card',
  CREATE_MNEMONIC = 'Create Mnemonic',
  RECOVER_MNEMONIC = 'Recover Mnemonic',
  RECOVER_ADDRESS = 'Recover Address',
  GET_PAIRING_PASSWORD = 'Get Pairing Password',
  GET_PAIRED_APPS = 'Get Paired Apps',
  EIP1559_COIN = 'Coin Transfer',
  EIP1559_TOKEN = 'Token Transfer',
  PERSONAL_SIGN = 'Personal Sign',
  SIGN_TYPED_DATA = 'Sign Typed Data',
  SEND_HEX = 'Send Hex',
}
